image:
  - Ubuntu
  - Visual Studio 2019
skip_tags: true
skip_commits:
  files:
    - .github/
pull_requests:
  do_not_increment_build_number: true
matrix:
  fast_finish: true
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  GITHUB_TOKEN:
    secure: 3bqzyVjmzE137kZ0lmMBKqM725nQd0hKAATVeE2trpWaPS+5bOpZfjy6zD5INfjV
  CHOCOLATEY_API_KEY:
    secure: CzGGbCfsVKyCTbY193kYveGQDN5ilsyI30J3FYdo9+IpGsDwi/knjzBqCQbztIzY
  CHOCOLATEY_SOURCE: https://push.chocolatey.org/

install:
  - sh: sudo apt-get update && sudo apt-get install -y libgit2-dev

build_script:
  - ps: .\build.ps1 --target=Init --verbosity=Diagnostic
  - sh: ./build.sh --target=Init --verbosity=Diagnostic
  - ps: .\build.ps1 --target=CI --verbosity=Diagnostic
  - sh: |
      if [ "$CI_LINUX" == "true" ]; then
        ./build.sh --target=CI --runtimes=linux-x64 --verbosity=Diagnostic
      else
        ./build.sh --target=CI --runtimes=osx-x64 --verbosity=Diagnostic
      fi

test: off

cache:
  - tools -> build/tools_addins.cake
